//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ShopTest
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invoice status.
    /// </summary>
    // *** Start programmer edit section *** (InvoiceStatus CustomAttributes)

    // *** End programmer edit section *** (InvoiceStatus CustomAttributes)
    public enum InvoiceStatus
    {
        
        // *** Start programmer edit section *** (InvoiceStatus.New CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.New CustomAttributes)
        New,
        
        // *** Start programmer edit section *** (InvoiceStatus.Issued CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Issued CustomAttributes)
        Issued,
        
        // *** Start programmer edit section *** (InvoiceStatus.Paused CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Paused CustomAttributes)
        Paused,
        
        // *** Start programmer edit section *** (InvoiceStatus.Ready CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Ready CustomAttributes)
        Ready,
        
        // *** Start programmer edit section *** (InvoiceStatus.Shipped CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Shipped CustomAttributes)
        Shipped,
    }
}
