//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ShopTest
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Position list.
    /// </summary>
    // *** Start programmer edit section *** (PositionList CustomAttributes)

    // *** End programmer edit section *** (PositionList CustomAttributes)
    public enum PositionList
    {
        
        // *** Start programmer edit section *** (PositionList.Storekeeper CustomAttributes)

        // *** End programmer edit section *** (PositionList.Storekeeper CustomAttributes)
        Storekeeper,
        
        // *** Start programmer edit section *** (PositionList.Manager CustomAttributes)

        // *** End programmer edit section *** (PositionList.Manager CustomAttributes)
        Manager,
    }
}
